client_id = "9c6563e1e7c06d1a6abb44fd9f2cba00"
application_url = "https://wishlist-shopify-app-ya92.onrender.com"
embedded = true
name = "wishlist"

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_orders"

[app_proxy]
url = "https://wishlist-shopify-app-ya92.onrender.com"
subpath = "wishlist"
prefix = "apps"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = [ "products/delete" ]

  [webhooks.privacy_compliance]
  customer_deletion_url = "/webhooks/customers/redact"
  customer_data_request_url = "/webhooks/customers/data_request"
  shop_deletion_url = "/webhooks/shop/redact"

[auth]
redirect_urls = [ "https://wishlist-shopify-app-ya92.onrender.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
